name: Run Gradle Tests

on:  
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:  # Name of the job
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Gradle
      run: ./gradlew build -e  # Use Gradle Wrapper for the build

    - name: Run tests
      run: ./gradlew test -e  # Use Gradle Wrapper for running tests
