name: Combined Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        run: echo "Hello ${{ inputs.name }}"

  build_and_test:  # Job for building and testing
    runs-on: ubuntu-latest
    needs: greet  # Ensure this job runs after the greet job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -e  # Added -e for detailed error output

      - name: Run tests
        run: mvn test -e  # Added -e for detailed error output
