name: Run tests

on:  
 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

  build:
    runs-on: ubuntu-latest
    needs: setup  # Ensure setup job runs first

    steps:
      - name: Build with Maven
        run: mvn clean install -e

  test:
    runs-on: ubuntu-latest
    needs: build  # Ensure build job runs first

    steps:
      - name: Run tests
        run: mvn test 
