name: Run tests

on:  
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:  # Name of the job
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install -e  # Added -e for detailed error output

    - name: Run tests
      run: mvn test -e  # Added -e for detailed error output
